# Session Signatures Debug
Shows the tower signature and assigned problem number for every session, for every subject.

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

from src.behavior_import.import_data import import_data
from src.behavior_import.extract_trials import (
    extract_trials_grouped_by_problem,
    choice_towers_signature,
    permutation_invariant_signature,
)
from fix_grid_maze_cohort_02_problems import fix_grid_maze_cohort_02_problems

folder_name = "3x3_maze_blocked_reward_bandit"
cohort = "cohort-02"
root = f"/Volumes/behrens/meg/{folder_name}/{cohort}/rawdata/"

subjects_data = import_data(root)
subjects_trials_by_problem = extract_trials_grouped_by_problem(subjects_data)
subjects_trials_by_problem = fix_grid_maze_cohort_02_problems(subjects_trials_by_problem)

[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-03_id-MY_04_R/ses-27_date-20260124/behav/._MY_04_R-2026-01-24-124422.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-03_id-MY_04_R/ses-55_date-20260209/behav/._MY_04_R-2026-02-09-103918.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-03_id-MY_04_R/ses-28_date-20260124/behav/._MY_04_R-2026-01-24-165301.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-03_id-MY_04_R/ses-12_date-20260116/behav/._MY_04_R-2026-01-16-143640.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-02_id-MY_04_L/ses-27_date-20260124/behav/._MY_04_L-2026-01-24-121012.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-02_id-MY_04_L/ses-27_date-20260124/behav/._MY_04_L-2026-01-24-122242.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-02_id-MY_04_L/ses-55_date-20260209/behav/._MY_04_L-2026-02-09-100738.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-02_id-MY_04_L/ses-28_date-20260124/behav/._MY_04_L-2026-01-24-162042.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-05_id-MY_05_L/ses-27_date-20260124/behav/._MY_05_L-2026-01-24-121300.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-05_id-MY_05_L/ses-55_date-20260209/behav/._MY_05_L-2026-02-09-100855.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-05_id-MY_05_L/ses-25_date-20260123/behav/._MY_05_L-2026-01-23-102323.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-05_id-MY_05_L/ses-28_date-20260124/behav/._MY_05_L-2026-01-24-160943.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-05_id-MY_05_L/ses-87_date-20260228/behav/._MY_05_L-2026-02-28-153110.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-05_id-MY_05_L/ses-87_date-20260228/behav/._MY_05_L-2026-02-28-154706.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-04_id-MY_05_N/ses-27_date-20260124/behav/._MY_05_N-2026-01-24-113906.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-04_id-MY_05_N/ses-55_date-20260209/behav/._MY_05_N-2026-02-09-093541.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-04_id-MY_05_N/ses-42_date-20260131/behav/._MY_05_N-2026-01-31-160735.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-04_id-MY_05_N/ses-28_date-20260124/behav/._MY_05_N-2026-01-24-153816.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-04_id-MY_05_N/ses-97_date-20260306/behav/._MY_05_N-2026-03-06-112255.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-01_id-MY_04_N/ses-27_date-20260124/behav/._MY_04_N-2026-01-24-113751.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-01_id-MY_04_N/ses-55_date-20260209/behav/._MY_04_N-2026-02-09-093451.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-01_id-MY_04_N/ses-28_date-20260124/behav/._MY_04_N-2026-01-24-154910.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-01_id-MY_04_N/ses-98_date-20260306/behav/._MY_04_N-2026-03-06-143023.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-01_id-MY_04_N/ses-32_date-20260126/behav/._MY_04_N-2026-01-26-132249.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-01_id-MY_04_N/ses-81_date-20260225/behav/._MY_04_N-2026-02-25-124103.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-06_id-MY_05_R/ses-27_date-20260124/behav/._MY_05_R-2026-01-24-124556.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-06_id-MY_05_R/ses-55_date-20260209/behav/._MY_05_R-2026-02-09-104055.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-06_id-MY_05_R/ses-28_date-20260124/behav/._MY_05_R-2026-01-24-164117.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[WARN] Failed to read /Volumes/behrens/meg/3x3_maze_blocked_reward_bandit/cohort-02/rawdata/sub-06_id-MY_05_R/ses-12_date-20260116/behav/._MY_05_R-2026-01-16-143704.tsv: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte.
[INFO] Processed 6 subjects(s), 612 session(s).
[INFO] Merging multiple files for subject MY_04_L, session ses-27_date-20260124
[WARNING] No trial information found for subject MY_04_L, session ses-84_date-20260226
[WARNING] No trial information found for subject MY_04_N, session ses-81_date-20260225
[WARNING] No trial information found for subject MY_05_N, session ses-1_date-20260111
[INFO] Merging multiple files for subject MY_05_N, session ses-2_date-20260111
[INFO] Merging multiple files for subject MY_05_N, session ses-33_date-20260127
[WARNING] No trial information found for subject MY_05_R, session ses-70_date-20260216
[INFO] Merging multiple files for subject MY_05_R, session ses-85_date-20260227
[INFO] Merging multiple files for subject MY_05_R, session ses-86_date-20260227
[INFO] Merging multiple files for subject MY_05_R, session ses-98_date-20260306
[INFO] Merging multiple files for subject MY_05_L, session ses-8_date-20260114
[INFO] Merging multiple files for subject MY_05_L, session ses-9_date-20260115
[INFO] Merging multiple files for subject MY_05_L, session ses-87_date-20260228
[INFO] Merging multiple files for subject MY_05_L, session ses-98_date-20260306
[WARNING] No trial information found for subject MY_05_L, session ses-100_date-20260309
[INFO] Merging multiple files for subject MY_04_R, session ses-30_date-20260125
[INFO] Merging multiple files for subject MY_04_R, session ses-32_date-20260126
[WARNING] No trial information found for subject MY_04_R, session ses-77_date-20260223
[WARNING] Skipping session ses-84_date-20260226 for subject MY_04_L due to missing trial information.
[WARNING] Skipping session ses-81_date-20260225 for subject MY_04_N due to missing trial information.
[WARNING] Skipping session ses-1_date-20260111 for subject MY_05_N due to missing trial information.
[WARNING] Skipping session ses-70_date-20260216 for subject MY_05_R due to missing trial information.
[WARNING] Skipping session ses-100_date-20260309 for subject MY_05_L due to missing trial information.
[WARNING] Skipping session ses-77_date-20260223 for subject MY_04_R due to missing trial information.

In [2]:
import pandas as pd
pd.set_option("display.max_rows", None)

def session_num(ses_key):
    return int(ses_key.split("ses-")[1].split("_")[0])

rows = []
for prob_num, prob_subjects in sorted(subjects_trials_by_problem.items()):
    for subj, sessions in sorted(prob_subjects.items()):
        for ses_key, sess in sorted(sessions.items(), key=lambda x: session_num(x[0])):
            raw = choice_towers_signature(sess)
            sig = permutation_invariant_signature(raw)
            rows.append({
                "subject": subj,
                "session": ses_key,
                "ses_num": session_num(ses_key),
                "problem": prob_num,
                "signature": sig,
            })

df = pd.DataFrame(rows).sort_values(["subject", "ses_num"]).reset_index(drop=True)
pd.set_option("display.max_rows", None)
df

,subject,session,ses_num,problem,signature
0,MY_04_L,ses-1_date-20260111,1,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
1,MY_04_L,ses-2_date-20260111,2,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
2,MY_04_L,ses-3_date-20260112,3,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
3,MY_04_L,ses-4_date-20260112,4,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
4,MY_04_L,ses-5_date-20260113,5,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
5,MY_04_L,ses-6_date-20260113,6,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
6,MY_04_L,ses-7_date-20260114,7,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
7,MY_04_L,ses-8_date-20260114,8,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
8,MY_04_L,ses-9_date-20260115,9,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
9,MY_04_L,ses-10_date-20260115,10,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
10,MY_04_L,ses-11_date-20260116,11,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
11,MY_04_L,ses-12_date-20260116,12,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
12,MY_04_L,ses-13_date-20260117,13,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
13,MY_04_L,ses-14_date-20260117,14,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
14,MY_04_L,ses-15_date-20260118,15,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
15,MY_04_L,ses-16_date-20260118,16,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
16,MY_04_L,ses-17_date-20260119,17,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
17,MY_04_L,ses-18_date-20260119,18,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
18,MY_04_L,ses-19_date-20260120,19,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
19,MY_04_L,ses-20_date-20260120,20,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
20,MY_04_L,ses-21_date-20260121,21,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
21,MY_04_L,ses-22_date-20260121,22,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
22,MY_04_L,ses-23_date-20260122,23,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
23,MY_04_L,ses-24_date-20260122,24,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
24,MY_04_L,ses-25_date-20260123,25,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
25,MY_04_L,ses-26_date-20260123,26,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
26,MY_04_L,ses-27_date-20260124,27,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
27,MY_04_L,ses-28_date-20260124,28,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
28,MY_04_L,ses-29_date-20260125,29,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
29,MY_04_L,ses-30_date-20260125,30,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
30,MY_04_L,ses-31_date-20260126,31,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
31,MY_04_L,ses-32_date-20260126,32,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
32,MY_04_L,ses-33_date-20260127,33,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
33,MY_04_L,ses-34_date-20260127,34,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
34,MY_04_L,ses-35_date-20260128,35,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
35,MY_04_L,ses-36_date-20260128,36,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
36,MY_04_L,ses-37_date-20260129,37,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
37,MY_04_L,ses-38_date-20260129,38,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
38,MY_04_L,ses-39_date-20260130,39,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
39,MY_04_L,ses-40_date-20260130,40,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
40,MY_04_L,ses-41_date-20260131,41,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
41,MY_04_L,ses-42_date-20260131,42,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
42,MY_04_L,ses-43_date-20260201,43,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
43,MY_04_L,ses-44_date-20260201,44,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
44,MY_04_L,ses-45_date-20260202,45,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
45,MY_04_L,ses-46_date-20260202,46,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
46,MY_04_L,ses-47_date-20260203,47,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
47,MY_04_L,ses-48_date-20260203,48,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
48,MY_04_L,ses-49_date-20260204,49,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
49,MY_04_L,ses-50_date-20260204,50,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
50,MY_04_L,ses-51_date-20260205,51,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
51,MY_04_L,ses-52_date-20260205,52,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
52,MY_04_L,ses-53_date-20260206,53,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
53,MY_04_L,ses-54_date-20260206,54,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
54,MY_04_L,ses-55_date-20260209,55,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
55,MY_04_L,ses-56_date-20260209,56,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
56,MY_04_L,ses-57_date-20260210,57,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))"
57,MY_04_L,ses-58_date-20260210,58,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
58,MY_04_L,ses-59_date-20260211,59,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
59,MY_04_L,ses-60_date-20260211,60,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
60,MY_04_L,ses-61_date-20260212,61,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
61,MY_04_L,ses-62_date-20260212,62,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
62,MY_04_L,ses-63_date-20260213,63,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
63,MY_04_L,ses-64_date-20260213,64,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
64,MY_04_L,ses-65_date-20260214,65,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
65,MY_04_L,ses-66_date-20260214,66,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
66,MY_04_L,ses-67_date-20260215,67,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
67,MY_04_L,ses-68_date-20260215,68,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
68,MY_04_L,ses-69_date-20260216,69,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
69,MY_04_L,ses-70_date-20260216,70,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
70,MY_04_L,ses-71_date-20260217,71,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
71,MY_04_L,ses-72_date-20260217,72,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
72,MY_04_L,ses-73_date-20260218,73,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
73,MY_04_L,ses-74_date-20260218,74,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
74,MY_04_L,ses-75_date-20260220,75,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
75,MY_04_L,ses-76_date-20260220,76,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
76,MY_04_L,ses-77_date-20260223,77,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
77,MY_04_L,ses-78_date-20260223,78,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
78,MY_04_L,ses-79_date-20260224,79,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
79,MY_04_L,ses-80_date-20260224,80,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
80,MY_04_L,ses-81_date-20260225,81,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
81,MY_04_L,ses-82_date-20260225,82,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
82,MY_04_L,ses-83_date-20260226,83,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
83,MY_04_L,ses-85_date-20260227,85,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
84,MY_04_L,ses-86_date-20260227,86,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
85,MY_04_L,ses-87_date-20260228,87,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
86,MY_04_L,ses-88_date-20260228,88,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
87,MY_04_L,ses-89_date-20260301,89,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
88,MY_04_L,ses-90_date-20260301,90,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
89,MY_04_L,ses-91_date-20260303,91,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
90,MY_04_L,ses-92_date-20260303,92,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
91,MY_04_L,ses-93_date-20260304,93,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
92,MY_04_L,ses-94_date-20260304,94,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
93,MY_04_L,ses-95_date-20260305,95,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
94,MY_04_L,ses-96_date-20260305,96,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
95,MY_04_L,ses-97_date-20260306,97,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
96,MY_04_L,ses-98_date-20260306,98,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
97,MY_04_L,ses-99_date-20260309,99,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
98,MY_04_L,ses-100_date-20260309,100,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
99,MY_04_L,ses-101_date-20260310,101,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
100,MY_04_L,ses-102_date-20260310,102,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
101,MY_04_N,ses-1_date-20260111,1,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
102,MY_04_N,ses-2_date-20260111,2,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
103,MY_04_N,ses-3_date-20260112,3,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
104,MY_04_N,ses-4_date-20260112,4,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
105,MY_04_N,ses-5_date-20260113,5,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
106,MY_04_N,ses-6_date-20260113,6,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
107,MY_04_N,ses-7_date-20260114,7,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
108,MY_04_N,ses-8_date-20260114,8,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
109,MY_04_N,ses-9_date-20260115,9,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
110,MY_04_N,ses-10_date-20260115,10,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
111,MY_04_N,ses-11_date-20260116,11,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
112,MY_04_N,ses-12_date-20260116,12,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
113,MY_04_N,ses-13_date-20260117,13,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
114,MY_04_N,ses-14_date-20260117,14,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
115,MY_04_N,ses-15_date-20260118,15,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
116,MY_04_N,ses-16_date-20260118,16,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
117,MY_04_N,ses-17_date-20260119,17,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
118,MY_04_N,ses-18_date-20260119,18,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
119,MY_04_N,ses-19_date-20260120,19,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
120,MY_04_N,ses-20_date-20260120,20,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
121,MY_04_N,ses-21_date-20260121,21,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
122,MY_04_N,ses-22_date-20260121,22,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
123,MY_04_N,ses-23_date-20260122,23,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
124,MY_04_N,ses-24_date-20260122,24,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
125,MY_04_N,ses-25_date-20260123,25,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
126,MY_04_N,ses-26_date-20260123,26,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
127,MY_04_N,ses-27_date-20260124,27,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
128,MY_04_N,ses-28_date-20260124,28,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
129,MY_04_N,ses-29_date-20260125,29,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
130,MY_04_N,ses-30_date-20260125,30,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
131,MY_04_N,ses-31_date-20260126,31,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
132,MY_04_N,ses-32_date-20260126,32,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
133,MY_04_N,ses-33_date-20260127,33,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
134,MY_04_N,ses-34_date-20260127,34,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
135,MY_04_N,ses-35_date-20260128,35,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
136,MY_04_N,ses-36_date-20260128,36,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
137,MY_04_N,ses-37_date-20260129,37,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))"
138,MY_04_N,ses-38_date-20260129,38,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
139,MY_04_N,ses-39_date-20260130,39,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
140,MY_04_N,ses-40_date-20260130,40,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
141,MY_04_N,ses-41_date-20260131,41,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
142,MY_04_N,ses-42_date-20260131,42,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
143,MY_04_N,ses-43_date-20260201,43,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
144,MY_04_N,ses-44_date-20260201,44,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))"
145,MY_04_N,ses-45_date-20260202,45,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))"
146,MY_04_N,ses-46_date-20260202,46,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))"
147,MY_04_N,ses-47_date-20260203,47,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))"
148,MY_04_N,ses-48_date-20260203,48,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))"
149,MY_04_N,ses-49_date-20260204,49,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))"
150,MY_04_N,ses-50_date-20260204,50,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))"
151,MY_04_N,ses-51_date-20260205,51,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))"
152,MY_04_N,ses-52_date-20260205,52,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
153,MY_04_N,ses-53_date-20260206,53,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
154,MY_04_N,ses-54_date-20260206,54,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
155,MY_04_N,ses-55_date-20260209,55,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
156,MY_04_N,ses-56_date-20260209,56,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
157,MY_04_N,ses-57_date-20260210,57,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
158,MY_04_N,ses-58_date-20260210,58,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
159,MY_04_N,ses-59_date-20260211,59,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
160,MY_04_N,ses-60_date-20260211,60,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
161,MY_04_N,ses-61_date-20260212,61,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
162,MY_04_N,ses-62_date-20260212,62,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
163,MY_04_N,ses-63_date-20260213,63,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
164,MY_04_N,ses-64_date-20260213,64,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
165,MY_04_N,ses-65_date-20260214,65,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
166,MY_04_N,ses-66_date-20260214,66,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))"
167,MY_04_N,ses-67_date-20260215,67,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
168,MY_04_N,ses-68_date-20260215,68,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
169,MY_04_N,ses-69_date-20260216,69,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
170,MY_04_N,ses-70_date-20260216,70,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
171,MY_04_N,ses-71_date-20260217,71,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
172,MY_04_N,ses-72_date-20260217,72,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
173,MY_04_N,ses-73_date-20260218,73,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))"
174,MY_04_N,ses-74_date-20260218,74,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
175,MY_04_N,ses-75_date-20260220,75,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
176,MY_04_N,ses-76_date-20260220,76,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
177,MY_04_N,ses-77_date-20260223,77,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
178,MY_04_N,ses-78_date-20260223,78,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
179,MY_04_N,ses-79_date-20260224,79,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
180,MY_04_N,ses-80_date-20260224,80,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))"
181,MY_04_N,ses-82_date-20260225,82,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))"
182,MY_04_N,ses-83_date-20260226,83,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))"
183,MY_04_N,ses-84_date-20260226,84,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))"
184,MY_04_N,ses-85_date-20260227,85,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))"
185,MY_04_N,ses-86_date-20260227,86,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))"
186,MY_04_N,ses-87_date-20260228,87,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))"
187,MY_04_N,ses-88_date-20260228,88,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))"
188,MY_04_N,ses-89_date-20260301,89,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))"
189,MY_04_N,ses-90_date-20260301,90,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))"
190,MY_04_N,ses-91_date-20260303,91,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))"
191,MY_04_N,ses-92_date-20260303,92,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))"
192,MY_04_N,ses-93_date-20260304,93,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))"
193,MY_04_N,ses-94_date-20260304,94,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))"
194,MY_04_N,ses-95_date-20260305,95,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))"
195,MY_04_N,ses-96_date-20260305,96,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))"
196,MY_04_N,ses-97_date-20260306,97,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))"
197,MY_04_N,ses-98_date-20260306,98,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))"
198,MY_04_N,ses-99_date-20260309,99,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))"
199,MY_04_N,ses-100_date-20260309,100,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))"
200,MY_04_N,ses-101_date-20260310,101,14,"(((A, 3), (B, 1), (B, 3)), (B, 2))"
201,MY_04_N,ses-102_date-20260310,102,14,"(((A, 3), (B, 1), (B, 3)), (B, 2))"
202,MY_04_R,ses-1_date-20260111,1,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
203,MY_04_R,ses-2_date-20260111,2,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
204,MY_04_R,ses-3_date-20260112,3,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
205,MY_04_R,ses-4_date-20260112,4,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
206,MY_04_R,ses-5_date-20260113,5,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
207,MY_04_R,ses-6_date-20260113,6,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
208,MY_04_R,ses-7_date-20260114,7,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
209,MY_04_R,ses-8_date-20260114,8,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
210,MY_04_R,ses-9_date-20260115,9,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
211,MY_04_R,ses-10_date-20260115,10,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
212,MY_04_R,ses-11_date-20260116,11,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
213,MY_04_R,ses-12_date-20260116,12,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
214,MY_04_R,ses-13_date-20260117,13,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
215,MY_04_R,ses-14_date-20260117,14,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
216,MY_04_R,ses-15_date-20260118,15,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
217,MY_04_R,ses-16_date-20260118,16,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
218,MY_04_R,ses-17_date-20260119,17,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
219,MY_04_R,ses-18_date-20260119,18,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
220,MY_04_R,ses-19_date-20260120,19,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
221,MY_04_R,ses-20_date-20260120,20,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
222,MY_04_R,ses-21_date-20260121,21,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
223,MY_04_R,ses-22_date-20260121,22,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
224,MY_04_R,ses-23_date-20260122,23,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
225,MY_04_R,ses-24_date-20260122,24,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
226,MY_04_R,ses-25_date-20260123,25,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
227,MY_04_R,ses-26_date-20260123,26,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
228,MY_04_R,ses-27_date-20260124,27,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
229,MY_04_R,ses-28_date-20260124,28,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))"
230,MY_04_R,ses-37_date-20260129,37,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
231,MY_04_R,ses-38_date-20260129,38,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
232,MY_04_R,ses-39_date-20260130,39,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
233,MY_04_R,ses-40_date-20260130,40,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
234,MY_04_R,ses-41_date-20260131,41,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
235,MY_04_R,ses-42_date-20260131,42,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
236,MY_04_R,ses-43_date-20260201,43,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
237,MY_04_R,ses-44_date-20260201,44,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
238,MY_04_R,ses-45_date-20260202,45,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))"
239,MY_04_R,ses-46_date-20260202,46,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
240,MY_04_R,ses-47_date-20260203,47,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
241,MY_04_R,ses-48_date-20260203,48,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
242,MY_04_R,ses-49_date-20260204,49,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
243,MY_04_R,ses-50_date-20260204,50,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
244,MY_04_R,ses-51_date-20260205,51,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
245,MY_04_R,ses-52_date-20260205,52,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
246,MY_04_R,ses-53_date-20260206,53,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
247,MY_04_R,ses-54_date-20260206,54,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))"
248,MY_04_R,ses-55_date-20260209,55,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
249,MY_04_R,ses-56_date-20260209,56,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
250,MY_04_R,ses-57_date-20260210,57,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
251,MY_04_R,ses-58_date-20260210,58,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
252,MY_04_R,ses-59_date-20260211,59,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
253,MY_04_R,ses-60_date-20260211,60,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
254,MY_04_R,ses-61_date-20260212,61,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))"
255,MY_04_R,ses-62_date-20260212,62,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
256,MY_04_R,ses-63_date-20260213,63,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
257,MY_04_R,ses-64_date-20260213,64,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
258,MY_04_R,ses-65_date-20260214,65,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
259,MY_04_R,ses-66_date-20260214,66,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
260,MY_04_R,ses-67_date-20260215,67,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
261,MY_04_R,ses-68_date-20260215,68,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))"
262,MY_04_R,ses-69_date-20260216,69,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))"
263,MY_04_R,ses-70_date-20260216,70,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))"
264,MY_04_R,ses-71_date-20260217,71,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))"
265,MY_04_R,ses-72_date-20260217,72,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))"
266,MY_04_R,ses-73_date-20260218,73,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))"

## Per-subject view
Shows each subject's sessions in chronological order with their assigned problem number and signature.

In [3]:
pd.set_option("display.max_rows", None)

for subj, grp in df.groupby("subject"):
    grp = grp.sort_values("ses_num").reset_index(drop=True)
    grp["prob_changed"] = grp["problem"] != grp["problem"].shift()
    grp["is_revisit"] = grp.duplicated(subset=["subject", "signature"], keep="first") & grp["signature"].notna()

    print(f"\n{'='*60}")
    print(f"  {subj}")
    print(f"{'='*60}")
    display(grp[["session", "ses_num", "problem", "signature", "prob_changed", "is_revisit"]])

============================================================
  MY_04_L
============================================================

,session,ses_num,problem,signature,prob_changed,is_revisit
0,ses-1_date-20260111,1,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",True,False
1,ses-2_date-20260111,2,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
2,ses-3_date-20260112,3,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
3,ses-4_date-20260112,4,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
4,ses-5_date-20260113,5,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
5,ses-6_date-20260113,6,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
6,ses-7_date-20260114,7,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
7,ses-8_date-20260114,8,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
8,ses-9_date-20260115,9,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
9,ses-10_date-20260115,10,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
10,ses-11_date-20260116,11,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
11,ses-12_date-20260116,12,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
12,ses-13_date-20260117,13,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
13,ses-14_date-20260117,14,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
14,ses-15_date-20260118,15,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
15,ses-16_date-20260118,16,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
16,ses-17_date-20260119,17,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
17,ses-18_date-20260119,18,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
18,ses-19_date-20260120,19,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
19,ses-20_date-20260120,20,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
20,ses-21_date-20260121,21,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
21,ses-22_date-20260121,22,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
22,ses-23_date-20260122,23,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
23,ses-24_date-20260122,24,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
24,ses-25_date-20260123,25,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",True,False
25,ses-26_date-20260123,26,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
26,ses-27_date-20260124,27,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
27,ses-28_date-20260124,28,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
28,ses-29_date-20260125,29,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
29,ses-30_date-20260125,30,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
30,ses-31_date-20260126,31,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
31,ses-32_date-20260126,32,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
32,ses-33_date-20260127,33,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
33,ses-34_date-20260127,34,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
34,ses-35_date-20260128,35,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
35,ses-36_date-20260128,36,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
36,ses-37_date-20260129,37,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",True,False
37,ses-38_date-20260129,38,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
38,ses-39_date-20260130,39,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
39,ses-40_date-20260130,40,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
40,ses-41_date-20260131,41,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
41,ses-42_date-20260131,42,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
42,ses-43_date-20260201,43,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
43,ses-44_date-20260201,44,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",True,False
44,ses-45_date-20260202,45,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
45,ses-46_date-20260202,46,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
46,ses-47_date-20260203,47,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
47,ses-48_date-20260203,48,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
48,ses-49_date-20260204,49,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
49,ses-50_date-20260204,50,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
50,ses-51_date-20260205,51,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
51,ses-52_date-20260205,52,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
52,ses-53_date-20260206,53,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
53,ses-54_date-20260206,54,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
54,ses-55_date-20260209,55,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
55,ses-56_date-20260209,56,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
56,ses-57_date-20260210,57,4,"(((A, 2), (B, 2), (C, 2)), (B, 1))",False,True
57,ses-58_date-20260210,58,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",True,False
58,ses-59_date-20260211,59,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
59,ses-60_date-20260211,60,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
60,ses-61_date-20260212,61,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
61,ses-62_date-20260212,62,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
62,ses-63_date-20260213,63,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
63,ses-64_date-20260213,64,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
64,ses-65_date-20260214,65,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
65,ses-66_date-20260214,66,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
66,ses-67_date-20260215,67,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",True,False
67,ses-68_date-20260215,68,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
68,ses-69_date-20260216,69,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
69,ses-70_date-20260216,70,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
70,ses-71_date-20260217,71,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
71,ses-72_date-20260217,72,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
72,ses-73_date-20260218,73,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",True,False
73,ses-74_date-20260218,74,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
74,ses-75_date-20260220,75,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
75,ses-76_date-20260220,76,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
76,ses-77_date-20260223,77,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
77,ses-78_date-20260223,78,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
78,ses-79_date-20260224,79,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
79,ses-80_date-20260224,80,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
80,ses-81_date-20260225,81,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
81,ses-82_date-20260225,82,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
82,ses-83_date-20260226,83,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
83,ses-85_date-20260227,85,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",True,False
84,ses-86_date-20260227,86,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
85,ses-87_date-20260228,87,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
86,ses-88_date-20260228,88,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
87,ses-89_date-20260301,89,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
88,ses-90_date-20260301,90,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
89,ses-91_date-20260303,91,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
90,ses-92_date-20260303,92,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
91,ses-93_date-20260304,93,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",True,False
92,ses-94_date-20260304,94,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
93,ses-95_date-20260305,95,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
94,ses-96_date-20260305,96,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
95,ses-97_date-20260306,97,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
96,ses-98_date-20260306,98,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
97,ses-99_date-20260309,99,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
98,ses-100_date-20260309,100,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
99,ses-101_date-20260310,101,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
100,ses-102_date-20260310,102,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True

============================================================
  MY_04_N
============================================================

,session,ses_num,problem,signature,prob_changed,is_revisit
0,ses-1_date-20260111,1,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",True,False
1,ses-2_date-20260111,2,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
2,ses-3_date-20260112,3,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
3,ses-4_date-20260112,4,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
4,ses-5_date-20260113,5,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
5,ses-6_date-20260113,6,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
6,ses-7_date-20260114,7,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
7,ses-8_date-20260114,8,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
8,ses-9_date-20260115,9,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
9,ses-10_date-20260115,10,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
10,ses-11_date-20260116,11,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
11,ses-12_date-20260116,12,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
12,ses-13_date-20260117,13,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
13,ses-14_date-20260117,14,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
14,ses-15_date-20260118,15,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
15,ses-16_date-20260118,16,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
16,ses-17_date-20260119,17,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
17,ses-18_date-20260119,18,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
18,ses-19_date-20260120,19,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
19,ses-20_date-20260120,20,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
20,ses-21_date-20260121,21,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
21,ses-22_date-20260121,22,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
22,ses-23_date-20260122,23,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
23,ses-24_date-20260122,24,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
24,ses-25_date-20260123,25,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",True,False
25,ses-26_date-20260123,26,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
26,ses-27_date-20260124,27,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
27,ses-28_date-20260124,28,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
28,ses-29_date-20260125,29,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
29,ses-30_date-20260125,30,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
30,ses-31_date-20260126,31,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
31,ses-32_date-20260126,32,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
32,ses-33_date-20260127,33,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
33,ses-34_date-20260127,34,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
34,ses-35_date-20260128,35,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
35,ses-36_date-20260128,36,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
36,ses-37_date-20260129,37,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
37,ses-38_date-20260129,38,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",True,False
38,ses-39_date-20260130,39,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
39,ses-40_date-20260130,40,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
40,ses-41_date-20260131,41,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
41,ses-42_date-20260131,42,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
42,ses-43_date-20260201,43,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
43,ses-44_date-20260201,44,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))",True,False
44,ses-45_date-20260202,45,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))",False,True
45,ses-46_date-20260202,46,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))",False,True
46,ses-47_date-20260203,47,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))",False,True
47,ses-48_date-20260203,48,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))",False,True
48,ses-49_date-20260204,49,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))",False,True
49,ses-50_date-20260204,50,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))",False,True
50,ses-51_date-20260205,51,4,"(((A, 3), (B, 3), (C, 3)), (B, 1))",False,True
51,ses-52_date-20260205,52,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",True,False
52,ses-53_date-20260206,53,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
53,ses-54_date-20260206,54,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
54,ses-55_date-20260209,55,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
55,ses-56_date-20260209,56,5,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
56,ses-57_date-20260210,57,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",True,False
57,ses-58_date-20260210,58,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
58,ses-59_date-20260211,59,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
59,ses-60_date-20260211,60,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
60,ses-61_date-20260212,61,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
61,ses-62_date-20260212,62,6,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
62,ses-63_date-20260213,63,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",True,False
63,ses-64_date-20260213,64,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
64,ses-65_date-20260214,65,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
65,ses-66_date-20260214,66,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
66,ses-67_date-20260215,67,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",True,False
67,ses-68_date-20260215,68,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
68,ses-69_date-20260216,69,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
69,ses-70_date-20260216,70,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
70,ses-71_date-20260217,71,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
71,ses-72_date-20260217,72,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
72,ses-73_date-20260218,73,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
73,ses-74_date-20260218,74,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",True,False
74,ses-75_date-20260220,75,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
75,ses-76_date-20260220,76,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
76,ses-77_date-20260223,77,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
77,ses-78_date-20260223,78,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
78,ses-79_date-20260224,79,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
79,ses-80_date-20260224,80,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
80,ses-82_date-20260225,82,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",True,False
81,ses-83_date-20260226,83,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
82,ses-84_date-20260226,84,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
83,ses-85_date-20260227,85,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
84,ses-86_date-20260227,86,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
85,ses-87_date-20260228,87,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
86,ses-88_date-20260228,88,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",True,False
87,ses-89_date-20260301,89,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
88,ses-90_date-20260301,90,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
89,ses-91_date-20260303,91,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
90,ses-92_date-20260303,92,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
91,ses-93_date-20260304,93,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",True,False
92,ses-94_date-20260304,94,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",False,True
93,ses-95_date-20260305,95,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",False,True
94,ses-96_date-20260305,96,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",False,True
95,ses-97_date-20260306,97,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",False,True
96,ses-98_date-20260306,98,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",True,False
97,ses-99_date-20260309,99,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",False,True
98,ses-100_date-20260309,100,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",False,True
99,ses-101_date-20260310,101,14,"(((A, 3), (B, 1), (B, 3)), (B, 2))",True,False
100,ses-102_date-20260310,102,14,"(((A, 3), (B, 1), (B, 3)), (B, 2))",False,True

============================================================
  MY_04_R
============================================================

,session,ses_num,problem,signature,prob_changed,is_revisit
0,ses-1_date-20260111,1,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",True,False
1,ses-2_date-20260111,2,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
2,ses-3_date-20260112,3,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
3,ses-4_date-20260112,4,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
4,ses-5_date-20260113,5,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
5,ses-6_date-20260113,6,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
6,ses-7_date-20260114,7,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
7,ses-8_date-20260114,8,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
8,ses-9_date-20260115,9,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
9,ses-10_date-20260115,10,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
10,ses-11_date-20260116,11,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
11,ses-12_date-20260116,12,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
12,ses-13_date-20260117,13,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
13,ses-14_date-20260117,14,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
14,ses-15_date-20260118,15,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
15,ses-16_date-20260118,16,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
16,ses-17_date-20260119,17,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
17,ses-18_date-20260119,18,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
18,ses-19_date-20260120,19,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
19,ses-20_date-20260120,20,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
20,ses-21_date-20260121,21,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
21,ses-22_date-20260121,22,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
22,ses-23_date-20260122,23,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
23,ses-24_date-20260122,24,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
24,ses-25_date-20260123,25,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
25,ses-26_date-20260123,26,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
26,ses-27_date-20260124,27,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
27,ses-28_date-20260124,28,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
28,ses-37_date-20260129,37,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",True,False
29,ses-38_date-20260129,38,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
30,ses-39_date-20260130,39,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
31,ses-40_date-20260130,40,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
32,ses-41_date-20260131,41,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
33,ses-42_date-20260131,42,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
34,ses-43_date-20260201,43,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
35,ses-44_date-20260201,44,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
36,ses-45_date-20260202,45,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
37,ses-46_date-20260202,46,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",True,False
38,ses-47_date-20260203,47,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
39,ses-48_date-20260203,48,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
40,ses-49_date-20260204,49,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
41,ses-50_date-20260204,50,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
42,ses-51_date-20260205,51,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
43,ses-52_date-20260205,52,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
44,ses-53_date-20260206,53,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
45,ses-54_date-20260206,54,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
46,ses-55_date-20260209,55,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",True,False
47,ses-56_date-20260209,56,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
48,ses-57_date-20260210,57,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
49,ses-58_date-20260210,58,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
50,ses-59_date-20260211,59,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
51,ses-60_date-20260211,60,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
52,ses-61_date-20260212,61,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
53,ses-62_date-20260212,62,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",True,False
54,ses-63_date-20260213,63,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
55,ses-64_date-20260213,64,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
56,ses-65_date-20260214,65,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
57,ses-66_date-20260214,66,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
58,ses-67_date-20260215,67,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
59,ses-68_date-20260215,68,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
60,ses-69_date-20260216,69,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",True,False
61,ses-70_date-20260216,70,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
62,ses-71_date-20260217,71,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
63,ses-72_date-20260217,72,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
64,ses-73_date-20260218,73,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
65,ses-74_date-20260218,74,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
66,ses-75_date-20260220,75,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
67,ses-76_date-20260220,76,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
68,ses-78_date-20260223,78,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",True,False
69,ses-79_date-20260224,79,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
70,ses-80_date-20260224,80,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
71,ses-81_date-20260225,81,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
72,ses-82_date-20260225,82,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",True,False
73,ses-83_date-20260226,83,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
74,ses-84_date-20260226,84,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
75,ses-85_date-20260227,85,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
76,ses-86_date-20260227,86,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
77,ses-87_date-20260228,87,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
78,ses-88_date-20260228,88,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
79,ses-89_date-20260301,89,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",True,False
80,ses-90_date-20260301,90,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
81,ses-91_date-20260303,91,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
82,ses-92_date-20260303,92,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
83,ses-93_date-20260304,93,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
84,ses-94_date-20260304,94,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
85,ses-95_date-20260305,95,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
86,ses-96_date-20260305,96,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
87,ses-97_date-20260306,97,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",True,False
88,ses-98_date-20260306,98,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
89,ses-99_date-20260309,99,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
90,ses-100_date-20260309,100,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
91,ses-101_date-20260310,101,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
92,ses-102_date-20260310,102,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True

============================================================
  MY_05_L
============================================================

,session,ses_num,problem,signature,prob_changed,is_revisit
0,ses-1_date-20260111,1,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",True,False
1,ses-2_date-20260111,2,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
2,ses-3_date-20260112,3,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
3,ses-4_date-20260112,4,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
4,ses-5_date-20260113,5,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
5,ses-6_date-20260113,6,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
6,ses-7_date-20260114,7,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
7,ses-8_date-20260114,8,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
8,ses-9_date-20260115,9,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
9,ses-10_date-20260115,10,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
10,ses-11_date-20260116,11,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
11,ses-12_date-20260116,12,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
12,ses-13_date-20260117,13,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
13,ses-14_date-20260117,14,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
14,ses-15_date-20260118,15,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
15,ses-16_date-20260118,16,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
16,ses-17_date-20260119,17,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
17,ses-18_date-20260119,18,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
18,ses-19_date-20260120,19,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
19,ses-20_date-20260120,20,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
20,ses-21_date-20260121,21,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
21,ses-22_date-20260121,22,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
22,ses-23_date-20260122,23,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
23,ses-24_date-20260122,24,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
24,ses-25_date-20260123,25,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",True,False
25,ses-26_date-20260123,26,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
26,ses-27_date-20260124,27,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
27,ses-28_date-20260124,28,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
28,ses-29_date-20260125,29,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
29,ses-30_date-20260125,30,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
30,ses-31_date-20260126,31,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
31,ses-32_date-20260126,32,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
32,ses-33_date-20260127,33,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
33,ses-34_date-20260127,34,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
34,ses-35_date-20260128,35,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
35,ses-36_date-20260128,36,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
36,ses-37_date-20260129,37,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
37,ses-38_date-20260129,38,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
38,ses-39_date-20260130,39,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
39,ses-40_date-20260130,40,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
40,ses-41_date-20260131,41,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
41,ses-42_date-20260131,42,2,"(((A, 1), (B, 1), (C, 1)), (B, 3))",False,True
42,ses-43_date-20260201,43,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",True,False
43,ses-44_date-20260201,44,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
44,ses-45_date-20260202,45,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
45,ses-46_date-20260202,46,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
46,ses-47_date-20260203,47,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
47,ses-48_date-20260203,48,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
48,ses-49_date-20260204,49,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
49,ses-50_date-20260204,50,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
50,ses-51_date-20260205,51,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",True,False
51,ses-52_date-20260205,52,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
52,ses-53_date-20260206,53,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
53,ses-54_date-20260206,54,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
54,ses-55_date-20260209,55,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
55,ses-56_date-20260209,56,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",True,False
56,ses-57_date-20260210,57,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
57,ses-58_date-20260210,58,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
58,ses-59_date-20260211,59,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
59,ses-60_date-20260211,60,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
60,ses-61_date-20260212,61,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
61,ses-62_date-20260212,62,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
62,ses-63_date-20260213,63,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
63,ses-64_date-20260213,64,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
64,ses-65_date-20260214,65,6,"(((A, 1), (A, 3), (C, 2)), (B, 2))",True,False
65,ses-66_date-20260214,66,6,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
66,ses-67_date-20260215,67,6,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
67,ses-68_date-20260215,68,6,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
68,ses-69_date-20260216,69,6,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
69,ses-70_date-20260216,70,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",True,False
70,ses-71_date-20260217,71,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
71,ses-72_date-20260217,72,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
72,ses-73_date-20260218,73,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
73,ses-74_date-20260218,74,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
74,ses-75_date-20260220,75,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
75,ses-76_date-20260220,76,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
76,ses-77_date-20260223,77,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",True,True
77,ses-78_date-20260223,78,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
78,ses-79_date-20260224,79,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
79,ses-80_date-20260224,80,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
80,ses-81_date-20260225,81,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
81,ses-82_date-20260225,82,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",True,False
82,ses-83_date-20260226,83,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
83,ses-84_date-20260226,84,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
84,ses-85_date-20260227,85,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
85,ses-86_date-20260227,86,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
86,ses-87_date-20260228,87,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",True,False
87,ses-88_date-20260228,88,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
88,ses-89_date-20260301,89,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",True,False
89,ses-90_date-20260301,90,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
90,ses-91_date-20260303,91,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
91,ses-92_date-20260303,92,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
92,ses-93_date-20260304,93,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",True,False
93,ses-94_date-20260304,94,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",False,True
94,ses-95_date-20260305,95,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",False,True
95,ses-96_date-20260305,96,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",True,False
96,ses-97_date-20260306,97,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",False,True
97,ses-98_date-20260306,98,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",False,True
98,ses-99_date-20260309,99,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",False,True
99,ses-101_date-20260310,101,14,"(((A, 3), (B, 1), (B, 3)), (B, 2))",True,False
100,ses-102_date-20260310,102,14,"(((A, 3), (B, 1), (B, 3)), (B, 2))",False,True

============================================================
  MY_05_N
============================================================

,session,ses_num,problem,signature,prob_changed,is_revisit
0,ses-2_date-20260111,2,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",True,False
1,ses-3_date-20260112,3,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
2,ses-4_date-20260112,4,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
3,ses-5_date-20260113,5,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
4,ses-6_date-20260113,6,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
5,ses-7_date-20260114,7,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
6,ses-8_date-20260114,8,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
7,ses-9_date-20260115,9,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
8,ses-10_date-20260115,10,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
9,ses-11_date-20260116,11,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
10,ses-12_date-20260116,12,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
11,ses-13_date-20260117,13,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
12,ses-14_date-20260117,14,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
13,ses-15_date-20260118,15,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
14,ses-16_date-20260118,16,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
15,ses-17_date-20260119,17,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
16,ses-18_date-20260119,18,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
17,ses-19_date-20260120,19,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
18,ses-20_date-20260120,20,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
19,ses-21_date-20260121,21,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
20,ses-22_date-20260121,22,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
21,ses-23_date-20260122,23,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
22,ses-24_date-20260122,24,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
23,ses-25_date-20260123,25,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
24,ses-26_date-20260123,26,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
25,ses-27_date-20260124,27,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
26,ses-28_date-20260124,28,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
27,ses-29_date-20260125,29,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
28,ses-30_date-20260125,30,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
29,ses-31_date-20260126,31,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",True,False
30,ses-32_date-20260126,32,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
31,ses-33_date-20260127,33,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
32,ses-34_date-20260127,34,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
33,ses-35_date-20260128,35,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
34,ses-36_date-20260128,36,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
35,ses-37_date-20260129,37,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
36,ses-38_date-20260129,38,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
37,ses-39_date-20260130,39,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
38,ses-40_date-20260130,40,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
39,ses-41_date-20260131,41,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
40,ses-42_date-20260131,42,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",True,False
41,ses-43_date-20260201,43,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
42,ses-44_date-20260201,44,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
43,ses-45_date-20260202,45,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
44,ses-46_date-20260202,46,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
45,ses-47_date-20260203,47,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
46,ses-48_date-20260203,48,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
47,ses-49_date-20260204,49,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
48,ses-50_date-20260204,50,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",True,False
49,ses-51_date-20260205,51,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
50,ses-52_date-20260205,52,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
51,ses-53_date-20260206,53,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
52,ses-54_date-20260206,54,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
53,ses-55_date-20260209,55,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",True,False
54,ses-56_date-20260209,56,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
55,ses-57_date-20260210,57,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
56,ses-58_date-20260210,58,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
57,ses-59_date-20260211,59,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
58,ses-60_date-20260211,60,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",True,False
59,ses-61_date-20260212,61,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
60,ses-62_date-20260212,62,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
61,ses-63_date-20260213,63,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
62,ses-64_date-20260213,64,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
63,ses-65_date-20260214,65,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
64,ses-66_date-20260214,66,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",True,False
65,ses-67_date-20260215,67,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
66,ses-68_date-20260215,68,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
67,ses-69_date-20260216,69,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
68,ses-70_date-20260216,70,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
69,ses-71_date-20260217,71,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
70,ses-72_date-20260217,72,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",True,False
71,ses-73_date-20260218,73,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
72,ses-74_date-20260218,74,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
73,ses-75_date-20260220,75,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
74,ses-76_date-20260220,76,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
75,ses-77_date-20260223,77,8,"(((A, 1), (A, 3), (C, 2)), (B, 2))",False,True
76,ses-78_date-20260223,78,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",True,False
77,ses-79_date-20260224,79,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
78,ses-80_date-20260224,80,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
79,ses-81_date-20260225,81,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
80,ses-82_date-20260225,82,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
81,ses-83_date-20260226,83,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
82,ses-84_date-20260226,84,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
83,ses-85_date-20260227,85,9,"(((A, 2), (B, 1), (C, 3)), (B, 2))",False,True
84,ses-86_date-20260227,86,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",True,False
85,ses-87_date-20260228,87,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
86,ses-88_date-20260228,88,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
87,ses-89_date-20260301,89,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
88,ses-90_date-20260301,90,10,"(((A, 2), (B, 3), (C, 2)), (B, 2))",False,True
89,ses-91_date-20260303,91,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",True,False
90,ses-92_date-20260303,92,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
91,ses-93_date-20260304,93,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
92,ses-94_date-20260304,94,11,"(((A, 1), (B, 1), (C, 1)), (B, 2))",False,True
93,ses-95_date-20260305,95,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",True,False
94,ses-96_date-20260305,96,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",False,True
95,ses-97_date-20260306,97,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",True,False
96,ses-98_date-20260306,98,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",True,True
97,ses-99_date-20260309,99,12,"(((A, 2), (B, 3), (C, 3)), (B, 2))",False,True
98,ses-100_date-20260309,100,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",True,True
99,ses-101_date-20260310,101,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",False,True
100,ses-102_date-20260310,102,13,"(((A, 1), (C, 1), (C, 2)), (B, 2))",False,True

============================================================
  MY_05_R
============================================================

,session,ses_num,problem,signature,prob_changed,is_revisit
0,ses-1_date-20260111,1,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",True,False
1,ses-2_date-20260111,2,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
2,ses-3_date-20260112,3,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
3,ses-4_date-20260112,4,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
4,ses-5_date-20260113,5,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
5,ses-6_date-20260113,6,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
6,ses-7_date-20260114,7,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
7,ses-8_date-20260114,8,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
8,ses-9_date-20260115,9,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
9,ses-10_date-20260115,10,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
10,ses-11_date-20260116,11,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
11,ses-12_date-20260116,12,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
12,ses-13_date-20260117,13,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
13,ses-14_date-20260117,14,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
14,ses-15_date-20260118,15,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
15,ses-16_date-20260118,16,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
16,ses-17_date-20260119,17,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
17,ses-18_date-20260119,18,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
18,ses-19_date-20260120,19,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
19,ses-20_date-20260120,20,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
20,ses-21_date-20260121,21,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
21,ses-22_date-20260121,22,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
22,ses-23_date-20260122,23,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
23,ses-24_date-20260122,24,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
24,ses-25_date-20260123,25,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
25,ses-26_date-20260123,26,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
26,ses-27_date-20260124,27,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
27,ses-28_date-20260124,28,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
28,ses-29_date-20260125,29,1,"(((A, 1), (A, 3), (C, 3)), (B, 2))",False,True
29,ses-37_date-20260129,37,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",True,False
30,ses-38_date-20260129,38,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
31,ses-39_date-20260130,39,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
32,ses-40_date-20260130,40,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
33,ses-41_date-20260131,41,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
34,ses-42_date-20260131,42,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
35,ses-43_date-20260201,43,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
36,ses-44_date-20260201,44,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
37,ses-45_date-20260202,45,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
38,ses-46_date-20260202,46,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
39,ses-47_date-20260203,47,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
40,ses-48_date-20260203,48,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
41,ses-49_date-20260204,49,2,"(((A, 2), (B, 2), (C, 2)), (B, 3))",False,True
42,ses-50_date-20260204,50,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",True,False
43,ses-51_date-20260205,51,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
44,ses-52_date-20260205,52,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
45,ses-53_date-20260206,53,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
46,ses-54_date-20260206,54,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
47,ses-55_date-20260209,55,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
48,ses-56_date-20260209,56,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
49,ses-57_date-20260210,57,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
50,ses-58_date-20260210,58,3,"(((A, 2), (C, 1), (C, 3)), (B, 2))",False,True
51,ses-59_date-20260211,59,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",True,False
52,ses-60_date-20260211,60,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
53,ses-61_date-20260212,61,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
54,ses-62_date-20260212,62,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
55,ses-63_date-20260213,63,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
56,ses-64_date-20260213,64,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
57,ses-65_date-20260214,65,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
58,ses-66_date-20260214,66,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
59,ses-67_date-20260215,67,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
60,ses-68_date-20260215,68,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
61,ses-69_date-20260216,69,4,"(((A, 1), (B, 3), (C, 2)), (B, 2))",False,True
62,ses-71_date-20260217,71,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",True,False
63,ses-72_date-20260217,72,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
64,ses-73_date-20260218,73,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
65,ses-74_date-20260218,74,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
66,ses-75_date-20260220,75,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
67,ses-76_date-20260220,76,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
68,ses-77_date-20260223,77,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
69,ses-78_date-20260223,78,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
70,ses-79_date-20260224,79,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
71,ses-80_date-20260224,80,5,"(((A, 1), (A, 2), (A, 3)), (B, 2))",False,True
72,ses-81_date-20260225,81,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",True,False
73,ses-82_date-20260225,82,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
74,ses-83_date-20260226,83,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
75,ses-84_date-20260226,84,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
76,ses-85_date-20260227,85,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
77,ses-86_date-20260227,86,6,"(((B, 1), (B, 3), (C, 2)), (B, 2))",False,True
78,ses-87_date-20260228,87,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",True,False
79,ses-88_date-20260228,88,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
80,ses-89_date-20260301,89,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
81,ses-90_date-20260301,90,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
82,ses-91_date-20260303,91,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
83,ses-92_date-20260303,92,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
84,ses-93_date-20260304,93,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
85,ses-94_date-20260304,94,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
86,ses-95_date-20260305,95,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
87,ses-96_date-20260305,96,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
88,ses-97_date-20260306,97,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
89,ses-98_date-20260306,98,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
90,ses-99_date-20260309,99,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
91,ses-100_date-20260309,100,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
92,ses-101_date-20260310,101,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True
93,ses-102_date-20260310,102,7,"(((A, 1), (C, 1), (C, 3)), (B, 2))",False,True

## Problem transition summary
Shows only the sessions where the problem number changed, per subject.

In [4]:
for subj, grp in df.groupby("subject"):
    grp = grp.sort_values("ses_num").reset_index(drop=True)
    transitions = grp[grp["problem"] != grp["problem"].shift()]

    print(f"\n{subj} ({len(grp['problem'].unique())} problems):")
    for _, row in transitions.iterrows():
        print(f"  Problem {row['problem']:2d} @ {row['session']}: {row['signature']}")

MY_04_L (9 problems):
  Problem  1 @ ses-1_date-20260111: ((('A', 1), ('A', 3), ('C', 3)), ('B', 2))
  Problem  2 @ ses-25_date-20260123: ((('A', 1), ('B', 1), ('C', 1)), ('B', 3))
  Problem  3 @ ses-37_date-20260129: ((('A', 2), ('C', 1), ('C', 3)), ('B', 2))
  Problem  4 @ ses-44_date-20260201: ((('A', 2), ('B', 2), ('C', 2)), ('B', 1))
  Problem  5 @ ses-58_date-20260210: ((('A', 1), ('B', 3), ('C', 2)), ('B', 2))
  Problem  6 @ ses-67_date-20260215: ((('A', 1), ('A', 2), ('A', 3)), ('B', 2))
  Problem  7 @ ses-73_date-20260218: ((('A', 1), ('C', 1), ('C', 3)), ('B', 2))
  Problem  8 @ ses-85_date-20260227: ((('A', 1), ('A', 3), ('C', 2)), ('B', 2))
  Problem  9 @ ses-93_date-20260304: ((('A', 2), ('B', 1), ('C', 3)), ('B', 2))

MY_04_N (14 problems):
  Problem  1 @ ses-1_date-20260111: ((('A', 1), ('A', 3), ('C', 3)), ('B', 2))
  Problem  2 @ ses-25_date-20260123: ((('A', 2), ('B', 2), ('C', 2)), ('B', 3))
  Problem  3 @ ses-38_date-20260129: ((('A', 2), ('C', 1), ('C', 3)), ('B', 2))
  Problem  4 @ ses-44_date-20260201: ((('A', 3), ('B', 3), ('C', 3)), ('B', 1))
  Problem  5 @ ses-52_date-20260205: ((('A', 1), ('B', 3), ('C', 2)), ('B', 2))
  Problem  6 @ ses-57_date-20260210: ((('A', 1), ('A', 2), ('A', 3)), ('B', 2))
  Problem  7 @ ses-63_date-20260213: ((('A', 1), ('C', 1), ('C', 3)), ('B', 2))
  Problem  8 @ ses-67_date-20260215: ((('A', 1), ('A', 3), ('C', 2)), ('B', 2))
  Problem  9 @ ses-74_date-20260218: ((('A', 2), ('B', 1), ('C', 3)), ('B', 2))
  Problem 10 @ ses-82_date-20260225: ((('A', 2), ('B', 3), ('C', 2)), ('B', 2))
  Problem 11 @ ses-88_date-20260228: ((('A', 1), ('B', 1), ('C', 1)), ('B', 2))
  Problem 12 @ ses-93_date-20260304: ((('A', 2), ('B', 3), ('C', 3)), ('B', 2))
  Problem 13 @ ses-98_date-20260306: ((('A', 1), ('C', 1), ('C', 2)), ('B', 2))
  Problem 14 @ ses-101_date-20260310: ((('A', 3), ('B', 1), ('B', 3)), ('B', 2))

MY_04_R (10 problems):
  Problem  1 @ ses-1_date-20260111: ((('A', 1), ('A', 3), ('C', 3)), ('B', 2))
  Problem  2 @ ses-37_date-20260129: ((('A', 1), ('B', 1), ('C', 1)), ('B', 3))
  Problem  3 @ ses-46_date-20260202: ((('A', 2), ('C', 1), ('C', 3)), ('B', 2))
  Problem  4 @ ses-55_date-20260209: ((('A', 1), ('B', 3), ('C', 2)), ('B', 2))
  Problem  5 @ ses-62_date-20260212: ((('A', 1), ('A', 2), ('A', 3)), ('B', 2))
  Problem  6 @ ses-69_date-20260216: ((('B', 1), ('B', 3), ('C', 2)), ('B', 2))
  Problem  7 @ ses-78_date-20260223: ((('A', 1), ('C', 1), ('C', 3)), ('B', 2))
  Problem  8 @ ses-82_date-20260225: ((('A', 1), ('A', 3), ('C', 2)), ('B', 2))
  Problem  9 @ ses-89_date-20260301: ((('A', 2), ('B', 1), ('C', 3)), ('B', 2))
  Problem 10 @ ses-97_date-20260306: ((('A', 2), ('B', 3), ('C', 2)), ('B', 2))

MY_05_L (14 problems):
  Problem  1 @ ses-1_date-20260111: ((('A', 1), ('A', 3), ('C', 3)), ('B', 2))
  Problem  2 @ ses-25_date-20260123: ((('A', 1), ('B', 1), ('C', 1)), ('B', 3))
  Problem  3 @ ses-43_date-20260201: ((('A', 2), ('C', 1), ('C', 3)), ('B', 2))
  Problem  4 @ ses-51_date-20260205: ((('A', 1), ('B', 3), ('C', 2)), ('B', 2))
  Problem  5 @ ses-56_date-20260209: ((('A', 1), ('A', 2), ('A', 3)), ('B', 2))
  Problem  6 @ ses-65_date-20260214: ((('A', 1), ('A', 3), ('C', 2)), ('B', 2))
  Problem  7 @ ses-70_date-20260216: ((('A', 1), ('C', 1), ('C', 3)), ('B', 2))
  Problem  8 @ ses-77_date-20260223: ((('A', 1), ('A', 3), ('C', 2)), ('B', 2))
  Problem  9 @ ses-82_date-20260225: ((('A', 2), ('B', 1), ('C', 3)), ('B', 2))
  Problem 10 @ ses-87_date-20260228: ((('A', 2), ('B', 3), ('C', 2)), ('B', 2))
  Problem 11 @ ses-89_date-20260301: ((('A', 1), ('B', 1), ('C', 1)), ('B', 2))
  Problem 12 @ ses-93_date-20260304: ((('A', 2), ('B', 3), ('C', 3)), ('B', 2))
  Problem 13 @ ses-96_date-20260305: ((('A', 1), ('C', 1), ('C', 2)), ('B', 2))
  Problem 14 @ ses-101_date-20260310: ((('A', 3), ('B', 1), ('B', 3)), ('B', 2))

MY_05_N (13 problems):
  Problem  1 @ ses-2_date-20260111: ((('A', 1), ('A', 3), ('C', 3)), ('B', 2))
  Problem  2 @ ses-31_date-20260126: ((('A', 2), ('B', 2), ('C', 2)), ('B', 3))
  Problem  3 @ ses-42_date-20260131: ((('A', 2), ('C', 1), ('C', 3)), ('B', 2))
  Problem  4 @ ses-50_date-20260204: ((('A', 1), ('B', 3), ('C', 2)), ('B', 2))
  Problem  5 @ ses-55_date-20260209: ((('A', 1), ('A', 2), ('A', 3)), ('B', 2))
  Problem  6 @ ses-60_date-20260211: ((('B', 1), ('B', 3), ('C', 2)), ('B', 2))
  Problem  7 @ ses-66_date-20260214: ((('A', 1), ('C', 1), ('C', 3)), ('B', 2))
  Problem  8 @ ses-72_date-20260217: ((('A', 1), ('A', 3), ('C', 2)), ('B', 2))
  Problem  9 @ ses-78_date-20260223: ((('A', 2), ('B', 1), ('C', 3)), ('B', 2))
  Problem 10 @ ses-86_date-20260227: ((('A', 2), ('B', 3), ('C', 2)), ('B', 2))
  Problem 11 @ ses-91_date-20260303: ((('A', 1), ('B', 1), ('C', 1)), ('B', 2))
  Problem 12 @ ses-95_date-20260305: ((('A', 2), ('B', 3), ('C', 3)), ('B', 2))
  Problem 13 @ ses-97_date-20260306: ((('A', 1), ('C', 1), ('C', 2)), ('B', 2))
  Problem 12 @ ses-98_date-20260306: ((('A', 2), ('B', 3), ('C', 3)), ('B', 2))
  Problem 13 @ ses-100_date-20260309: ((('A', 1), ('C', 1), ('C', 2)), ('B', 2))

MY_05_R (7 problems):
  Problem  1 @ ses-1_date-20260111: ((('A', 1), ('A', 3), ('C', 3)), ('B', 2))
  Problem  2 @ ses-37_date-20260129: ((('A', 2), ('B', 2), ('C', 2)), ('B', 3))
  Problem  3 @ ses-50_date-20260204: ((('A', 2), ('C', 1), ('C', 3)), ('B', 2))
  Problem  4 @ ses-59_date-20260211: ((('A', 1), ('B', 3), ('C', 2)), ('B', 2))
  Problem  5 @ ses-71_date-20260217: ((('A', 1), ('A', 2), ('A', 3)), ('B', 2))
  Problem  6 @ ses-81_date-20260225: ((('B', 1), ('B', 3), ('C', 2)), ('B', 2))
  Problem  7 @ ses-87_date-20260228: ((('A', 1), ('C', 1), ('C', 3)), ('B', 2))

## Signature consistency check
Flags any problems where a subject has more than one signature (should never happen).

In [5]:
issues = []
for (subj, prob), grp in df.groupby(["subject", "problem"]):
    sigs = grp["signature"].dropna().unique()
    if len(sigs) > 1:
        issues.append({"subject": subj, "problem": prob, "signatures": list(sigs)})

if issues:
    print("ISSUES FOUND:")
    for issue in issues:
        print(f"  {issue['subject']} Problem {issue['problem']}: {issue['signatures']}")
else:
    print("All good — every subject has a single signature per problem.")

All good — every subject has a single signature per problem.

In [6]:
import json
for ses_key in ["ses-25_date-20260123", "ses-26_date-20260123"]:
    sess = subjects_data["MY_05_L"][ses_key]
    print(f"{ses_key}: initiation_tower={sess.get('initiation_tower')}")

ses-25_date-20260123: initiation_tower=B3
ses-26_date-20260123: initiation_tower=B3

In [7]:
import json
sess_df = subjects_data["MY_05_L"]["ses-25_date-20260123"]["df"]
if not isinstance(sess_df, list):
    sess_df = [sess_df]
for df in sess_df:
    mask = (df.get("type") == "variable") & (df.get("subtype") == "run_start")
    if mask.any():
        run_start = json.loads(df.loc[mask, "content"].iloc[0])
        print({k: v for k, v in run_start.items() if "init" in k.lower()})

{'init_cue_dur': 500.0}